/*
    This script handles the recipes for Extended Crafting Recipes for Creative Items

    Note: These scripts are created and for the usage in modpacks curated by Team 8Bit. 
    You can use these scripts for reference and for learning but not for copying and 
    pasting and claiming as your own.
*/

import mods.extendedcrafting.TableCrafting;

function init() {

/* Creative Mill */
mods.extendedcrafting.TableCrafting.addShaped(0, <extrautils2:passivegenerator:6>, [
	[<extrautils2:passivegenerator:5>, <extrautils2:passivegenerator:7>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <extrautils2:passivegenerator:4>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <extrautils2:passivegenerator:7>, <extrautils2:passivegenerator:5>], 
	[<extrautils2:passivegenerator:7>, <extrautils2:unstableingots:2>, <ore:ingotEvilMetal>, <ore:ingotEvilMetal>, <extrautils2:passivegenerator:3>, <ore:ingotEvilMetal>, <ore:ingotEvilMetal>, <extrautils2:unstableingots:2>, <extrautils2:passivegenerator:7>], 
	[<ore:ingotCrystaltine>, <projecte:item.pe_body_stone>, <extrautils2:unstableingots:2>, <actuallyadditions:item_player_probe>, <extrautils2:passivegenerator:2>, <actuallyadditions:item_player_probe>, <extrautils2:unstableingots:2>, <projecte:item.pe_mind_stone>, <ore:ingotCrystaltine>], 
	[<ore:ingotCrystaltine>, <extendedcrafting:frame>, <extrautils2:suncrystal>, <extrautils2:unstableingots:2>, <extrautils2:passivegenerator:8>, <extrautils2:unstableingots:2>, <extrautils2:suncrystal>, <extendedcrafting:frame>, <ore:ingotCrystaltine>], 
	[<extrautils2:passivegenerator:4>, <extrautils2:passivegenerator:3>, <extrautils2:passivegenerator:2>, <extrautils2:passivegenerator:8>, <extendedcrafting:singularity_ultimate>, <extrautils2:passivegenerator:8>, <extrautils2:passivegenerator:2>, <extrautils2:passivegenerator:3>, <extrautils2:passivegenerator:4>], 
	[<ore:ingotCrystaltine>, <extendedcrafting:frame>, <extrautils2:suncrystal>, <extrautils2:unstableingots:2>, <extrautils2:passivegenerator:8>, <extrautils2:unstableingots:2>, <extrautils2:suncrystal>, <extendedcrafting:frame>, <ore:ingotCrystaltine>], 
	[<ore:ingotCrystaltine>, <projecte:item.pe_soul_stone>, <extrautils2:unstableingots:2>, <actuallyadditions:item_player_probe>, <extrautils2:passivegenerator:2>, <actuallyadditions:item_player_probe>, <extrautils2:unstableingots:2>, <projecte:item.pe_life_stone>, <ore:ingotCrystaltine>], 
	[<extrautils2:passivegenerator:7>, <extrautils2:unstableingots:2>, <ore:ingotEvilMetal>, <ore:ingotEvilMetal>, <extrautils2:passivegenerator:3>, <ore:ingotEvilMetal>, <ore:ingotEvilMetal>, <extrautils2:unstableingots:2>, <extrautils2:passivegenerator:7>], 
	[<extrautils2:passivegenerator:5>, <extrautils2:passivegenerator:7>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <extrautils2:passivegenerator:4>, <ore:ingotCrystaltine>, <ore:ingotCrystaltine>, <extrautils2:passivegenerator:7>, <extrautils2:passivegenerator:5>]
]);

/* Creative Model Learner */
mods.extendedcrafting.TableCrafting.addShaped(0, <deepmoblearning:creative_model_learner>, [
	[<deepmoblearning:data_model_blank>, <deepmoblearning:pristine_matter_tinker_slime>, <deepmoblearning:pristine_matter_thermal_elemental>, <deepmoblearning:pristine_matter_guardian>, <deepmoblearning:pristine_matter_shulker>, <deepmoblearning:pristine_matter_guardian>, <deepmoblearning:pristine_matter_thermal_elemental>, <deepmoblearning:pristine_matter_tinker_slime>, <deepmoblearning:data_model_blank>], 
	[<deepmoblearning:infused_ingot_block>, <deepmoblearning:pristine_matter_enderman>, <deepmoblearning:pristine_matter_ghast>, <deepmoblearning:pristine_matter_wither>, <deepmoblearning:pristine_matter_blaze>, <deepmoblearning:pristine_matter_wither>, <deepmoblearning:pristine_matter_ghast>, <deepmoblearning:pristine_matter_enderman>, <deepmoblearning:infused_ingot_block>], 
	[<deepmoblearning:infused_ingot_block>, <deepmoblearning:pristine_matter_wither_skeleton>, <deepmoblearning:pristine_matter_witch>, <deepmoblearning:pristine_matter_slime>, <deepmoblearning:pristine_matter_creeper>, <deepmoblearning:pristine_matter_slime>, <deepmoblearning:pristine_matter_witch>, <deepmoblearning:pristine_matter_wither_skeleton>, <deepmoblearning:infused_ingot_block>], 
	[<deepmoblearning:infused_ingot_block>, <deepmoblearning:pristine_matter_dragon>, <deepmoblearning:pristine_matter_spider>, <deepmoblearning:pristine_matter_skeleton>, <deepmoblearning:pristine_matter_zombie>, <deepmoblearning:pristine_matter_skeleton>, <deepmoblearning:pristine_matter_spider>, <deepmoblearning:pristine_matter_dragon>, <deepmoblearning:infused_ingot_block>], 
	[<deepmoblearning:pristine_matter_shulker>, <deepmoblearning:pristine_matter_blaze>, <deepmoblearning:pristine_matter_creeper>, <deepmoblearning:pristine_matter_zombie>, <extendedcrafting:singularity_ultimate>, <deepmoblearning:pristine_matter_zombie>, <deepmoblearning:pristine_matter_creeper>, <deepmoblearning:pristine_matter_blaze>, <deepmoblearning:pristine_matter_shulker>], 
	[<deepmoblearning:infused_ingot_block>, <deepmoblearning:pristine_matter_dragon>, <deepmoblearning:pristine_matter_spider>, <deepmoblearning:pristine_matter_skeleton>, <deepmoblearning:pristine_matter_zombie>, <deepmoblearning:pristine_matter_skeleton>, <deepmoblearning:pristine_matter_spider>, <deepmoblearning:pristine_matter_dragon>, <deepmoblearning:infused_ingot_block>], 
	[<deepmoblearning:infused_ingot_block>, <deepmoblearning:pristine_matter_wither_skeleton>, <deepmoblearning:pristine_matter_witch>, <deepmoblearning:pristine_matter_slime>, <deepmoblearning:pristine_matter_creeper>, <deepmoblearning:pristine_matter_slime>, <deepmoblearning:pristine_matter_witch>, <deepmoblearning:pristine_matter_wither_skeleton>, <deepmoblearning:infused_ingot_block>], 
	[<deepmoblearning:infused_ingot_block>, <deepmoblearning:pristine_matter_enderman>, <deepmoblearning:pristine_matter_ghast>, <deepmoblearning:pristine_matter_wither>, <deepmoblearning:pristine_matter_blaze>, <deepmoblearning:pristine_matter_wither>, <deepmoblearning:pristine_matter_ghast>, <deepmoblearning:pristine_matter_enderman>, <deepmoblearning:infused_ingot_block>], 
	[<deepmoblearning:data_model_blank>, <deepmoblearning:pristine_matter_tinker_slime>, <deepmoblearning:pristine_matter_thermal_elemental>, <deepmoblearning:pristine_matter_guardian>, <deepmoblearning:pristine_matter_shulker>, <deepmoblearning:pristine_matter_guardian>, <deepmoblearning:pristine_matter_thermal_elemental>, <deepmoblearning:pristine_matter_tinker_slime>, <deepmoblearning:data_model_blank>]
]);

/* Creative Sacrificial Dagger */
mods.extendedcrafting.TableCrafting.addShaped(0, <bloodmagic:sacrificial_dagger:1>, [
	[<bloodmagic:slate:2>, <bloodmagic:slate:2>, <bloodmagic:slate:2>, <bloodmagic:slate:2>, <bloodmagic:slate:2>, <bloodmagic:slate:2>, <bloodmagic:slate:2>, <bloodmagic:slate:2>, <bloodmagic:slate:2>], 
	[<bloodmagic:slate:2>, <bloodmagic:blood_rune:6>, <bloodmagic:decorative_brick>, <bloodmagic:decorative_brick>, <bloodmagic:monster_soul>, <bloodmagic:decorative_brick>, <bloodmagic:decorative_brick>, <bloodmagic:blood_rune:6>, <bloodmagic:slate:2>], 
	[<bloodmagic:slate:2>, <bloodmagic:decorative_brick>, <bloodmagic:blood_orb>, <bloodmagic:blood_orb>, <bloodmagic:blood_orb>, <bloodmagic:blood_orb>, <bloodmagic:blood_orb>, <bloodmagic:decorative_brick>, <bloodmagic:slate:2>], 
	[<bloodmagic:slate:2>, <bloodmagic:decorative_brick>, <bloodmagic:blood_orb>, <bloodmagic:sacrificial_dagger>, <bloodmagic:sacrificial_dagger>, <bloodmagic:sacrificial_dagger>, <bloodmagic:blood_orb>, <bloodmagic:decorative_brick>, <bloodmagic:slate:2>], 
	[<bloodmagic:slate:2>, <bloodmagic:monster_soul>, <bloodmagic:blood_orb>, <bloodmagic:sacrificial_dagger>, <extendedcrafting:singularity_ultimate>, <bloodmagic:sacrificial_dagger>, <bloodmagic:blood_orb>, <bloodmagic:monster_soul>, <bloodmagic:slate:2>], 
	[<bloodmagic:slate:2>, <bloodmagic:decorative_brick>, <bloodmagic:blood_orb>, <bloodmagic:sacrificial_dagger>, <bloodmagic:sacrificial_dagger>, <bloodmagic:sacrificial_dagger>, <bloodmagic:blood_orb>, <bloodmagic:decorative_brick>, <bloodmagic:slate:2>], 
	[<bloodmagic:slate:2>, <bloodmagic:decorative_brick>, <bloodmagic:blood_orb>, <bloodmagic:blood_orb>, <bloodmagic:blood_orb>, <bloodmagic:blood_orb>, <bloodmagic:blood_orb>, <bloodmagic:decorative_brick>, <bloodmagic:slate:2>], 
	[<bloodmagic:slate:2>, <bloodmagic:blood_rune:6>, <bloodmagic:decorative_brick>, <bloodmagic:decorative_brick>, <bloodmagic:monster_soul>, <bloodmagic:decorative_brick>, <bloodmagic:decorative_brick>, <bloodmagic:blood_rune:6>, <bloodmagic:slate:2>], 
	[<bloodmagic:slate:2>, <bloodmagic:slate:2>, <bloodmagic:slate:2>, <bloodmagic:slate:2>, <bloodmagic:slate:2>, <bloodmagic:slate:2>, <bloodmagic:slate:2>, <bloodmagic:slate:2>, <bloodmagic:slate:2>]
]);

/* Creative Wireless Crafting Terminal */
mods.extendedcrafting.TableCrafting.addShaped(0, <wct:wct_creative>, [
	[<wct:wct>, <appliedenergistics2:material:22>, <appliedenergistics2:material:24>, <appliedenergistics2:material:23>, <appliedenergistics2:wireless_access_point>, <appliedenergistics2:material:23>, <appliedenergistics2:material:24>, <appliedenergistics2:material:22>, <wct:wct>], 
	[<appliedenergistics2:material:22>, <appliedenergistics2:material:42>, <appliedenergistics2:material:42>, <appliedenergistics2:material:42>, <appliedenergistics2:material:42>, <appliedenergistics2:material:42>, <appliedenergistics2:material:42>, <appliedenergistics2:material:42>, <appliedenergistics2:material:22>], 
	[<appliedenergistics2:material:24>, <appliedenergistics2:material:42>, <appliedenergistics2:dense_energy_cell>, <appliedenergistics2:quantum_link>, <appliedenergistics2:material:48>, <appliedenergistics2:quantum_link>, <appliedenergistics2:dense_energy_cell>, <appliedenergistics2:material:42>, <appliedenergistics2:material:24>], 
	[<appliedenergistics2:material:23>, <appliedenergistics2:material:42>, <appliedenergistics2:quantum_link>, <ae2wtlib:infinity_booster_card>, <ae2wtlib:infinity_booster_card>, <ae2wtlib:infinity_booster_card>, <appliedenergistics2:quantum_link>, <appliedenergistics2:material:42>, <appliedenergistics2:material:23>], 
	[<appliedenergistics2:wireless_access_point>, <appliedenergistics2:material:42>, <appliedenergistics2:material:48>, <ae2wtlib:infinity_booster_card>, <extendedcrafting:singularity_ultimate>, <ae2wtlib:infinity_booster_card>, <appliedenergistics2:material:48>, <appliedenergistics2:material:42>, <appliedenergistics2:wireless_access_point>], 
	[<appliedenergistics2:material:23>, <appliedenergistics2:material:42>, <appliedenergistics2:quantum_link>, <ae2wtlib:infinity_booster_card>, <ae2wtlib:infinity_booster_card>, <ae2wtlib:infinity_booster_card>, <appliedenergistics2:quantum_link>, <appliedenergistics2:material:42>, <appliedenergistics2:material:23>], 
	[<appliedenergistics2:material:24>, <appliedenergistics2:material:42>, <appliedenergistics2:dense_energy_cell>, <appliedenergistics2:quantum_link>, <appliedenergistics2:material:48>, <appliedenergistics2:quantum_link>, <appliedenergistics2:dense_energy_cell>, <appliedenergistics2:material:42>, <appliedenergistics2:material:24>], 
	[<appliedenergistics2:material:22>, <appliedenergistics2:material:42>, <appliedenergistics2:material:42>, <appliedenergistics2:material:42>, <appliedenergistics2:material:42>, <appliedenergistics2:material:42>, <appliedenergistics2:material:42>, <appliedenergistics2:material:42>, <appliedenergistics2:material:22>], 
	[<wct:wct>, <appliedenergistics2:material:22>, <appliedenergistics2:material:24>, <appliedenergistics2:material:23>, <appliedenergistics2:wireless_access_point>, <appliedenergistics2:material:23>, <appliedenergistics2:material:24>, <appliedenergistics2:material:22>, <wct:wct>]
]);

/* Creative Modifier */
mods.extendedcrafting.TableCrafting.addShaped(0, <tconstruct:materials:50>, [
	[<tconstruct:cast>, <tconstruct:cast>, <tconstruct:materials:17>, <tconstruct:materials:17>, <tconstruct:materials:17>, <tconstruct:materials:17>, <tconstruct:materials:17>, <tconstruct:cast>, <tconstruct:cast>], 
	[<tconstruct:cast>, <tconstruct:cast>, <tconstruct:materials:19>, <tconstruct:materials:19>, <tconstruct:materials:19>, <tconstruct:materials:19>, <tconstruct:materials:19>, <tconstruct:cast>, <tconstruct:cast>], 
	[<tconstruct:cast>, <tconstruct:cast>, <tconstruct:materials:16>, <tconstruct:materials:10>, <tconstruct:materials:10>, <tconstruct:materials:10>, <tconstruct:materials:16>, <tconstruct:cast>, <tconstruct:cast>], 
	[<tconstruct:cast>, <tconstruct:cast>, <tconstruct:materials:16>, <tconstruct:materials:10>, <tconstruct:materials:10>, <tconstruct:materials:10>, <tconstruct:materials:16>, <tconstruct:cast>, <tconstruct:cast>], 
	[<tconstruct:cast>, <tconstruct:cast>, <tconstruct:materials:11>, <tconstruct:materials:11>, <extendedcrafting:singularity_ultimate>, <tconstruct:materials:11>, <tconstruct:materials:11>, <tconstruct:cast>, <tconstruct:cast>], 
	[<tconstruct:cast>, <tconstruct:cast>, <tconstruct:materials:16>, <tconstruct:materials:9>, <tconstruct:materials:9>, <tconstruct:materials:9>, <tconstruct:materials:16>, <tconstruct:cast>, <tconstruct:cast>], 
	[<tconstruct:cast>, <tconstruct:cast>, <tconstruct:materials:16>, <tconstruct:materials:9>, <tconstruct:materials:9>, <tconstruct:materials:9>, <tconstruct:materials:16>, <tconstruct:cast>, <tconstruct:cast>], 
	[<tconstruct:cast>, <tconstruct:cast>, <tconstruct:materials:19>, <tconstruct:materials:19>, <tconstruct:materials:19>, <tconstruct:materials:19>, <tconstruct:materials:19>, <tconstruct:cast>, <tconstruct:cast_custom>], 
	[<tconstruct:cast_custom:3>, <tconstruct:cast_custom:4>, <tconstruct:materials:17>, <tconstruct:materials:17>, <tconstruct:materials:17>, <tconstruct:materials:17>, <tconstruct:materials:17>, <tconstruct:cast>, <tconstruct:cast_custom:2>]
]);

/* Creative Energy Cube */
mods.extendedcrafting.TableCrafting.addShaped(0, <mekanism:energycube>.withTag({tier: 4, mekData: {energyStored: 1.7976931348623157E308}}), [
	[<mekanism:energycube>.withTag({tier: 3, mekData: {energyStored: 1.28E8}}), <mekanism:basicblock2:3>.withTag({tier: 3}), <mekanism:basicblock2:3>.withTag({tier: 3}), <mekanism:basicblock2:3>.withTag({tier: 3}), <environmentaltech:solar_cont_6>, <mekanism:basicblock2:3>.withTag({tier: 3}), <mekanism:basicblock2:3>.withTag({tier: 3}), <mekanism:basicblock2:3>.withTag({tier: 3}), <mekanism:energycube>.withTag({tier: 3, mekData: {energyStored: 1.28E8}})], 
	[<mekanism:basicblock2:3>.withTag({tier: 3}), <draconicevolution:draconic_energy_core>, <draconicevolution:draconic_energy_core>, <draconicevolution:draconic_energy_core>, <nuclearcraft:solid_fission_cell>, <draconicevolution:draconic_energy_core>, <draconicevolution:draconic_energy_core>, <draconicevolution:draconic_energy_core>, <mekanism:basicblock2:3>.withTag({tier: 3})], 
	[<mekanism:basicblock2:3>.withTag({tier: 3}), <draconicevolution:draconic_energy_core>, <projectex:power_flower:15>, <actuallyadditions:block_crystal_empowered:4>, <rftools:powercell_advanced>, <actuallyadditions:block_crystal_empowered:4>, <integrateddynamics:energy_battery>.withTag({energy: 4000000, capacity: 4000000}), <draconicevolution:draconic_energy_core>, <mekanism:basicblock2:3>.withTag({tier: 3})], 
	[<mekanism:basicblock2:3>.withTag({tier: 3}), <draconicevolution:draconic_energy_core>, <actuallyadditions:block_crystal_empowered:4>, <nuclearcraft:depleted_fuel_curium:5>, <industrialforegoing:energy_field_addon>, <nuclearcraft:depleted_fuel_curium:5>, <actuallyadditions:block_crystal_empowered:4>, <draconicevolution:draconic_energy_core>, <mekanism:basicblock2:3>.withTag({tier: 3})], 
	[<draconicevolution:reactor_core>, <draconicevolution:reactor_component:1>, <enderio:block_cap_bank:3>, <industrialforegoing:energy_field_addon>, <extendedcrafting:singularity_ultimate>, <industrialforegoing:energy_field_addon>, <enderio:block_cap_bank:3>, <draconicevolution:reactor_component:1>, <draconicevolution:reactor_core>], 
	[<mekanism:basicblock2:3>.withTag({tier: 3}), <draconicevolution:draconic_energy_core>, <actuallyadditions:block_crystal_empowered:4>, <nuclearcraft:depleted_fuel_curium:5>, <industrialforegoing:energy_field_addon>, <nuclearcraft:depleted_fuel_curium:5>, <actuallyadditions:block_crystal_empowered:4>, <draconicevolution:draconic_energy_core>, <mekanism:basicblock2:3>.withTag({tier: 3})], 
	[<mekanism:basicblock2:3>.withTag({tier: 3}), <draconicevolution:draconic_energy_core>, <integrateddynamics:energy_battery>.withTag({energy: 4000000, capacity: 4000000}), <actuallyadditions:block_crystal_empowered:4>, <rftools:powercell_advanced>, <actuallyadditions:block_crystal_empowered:4>, <projectex:power_flower:15>, <draconicevolution:draconic_energy_core>, <mekanism:basicblock2:3>.withTag({tier: 3})], 
	[<mekanism:basicblock2:3>.withTag({tier: 3}), <draconicevolution:draconic_energy_core>, <draconicevolution:draconic_energy_core>, <draconicevolution:draconic_energy_core>, <nuclearcraft:solid_fission_cell>, <draconicevolution:draconic_energy_core>, <draconicevolution:draconic_energy_core>, <draconicevolution:draconic_energy_core>, <mekanism:basicblock2:3>.withTag({tier: 3})], 
	[<mekanism:energycube>.withTag({tier: 3, mekData: {energyStored: 1.28E8}}), <mekanism:basicblock2:3>.withTag({tier: 3}), <mekanism:basicblock2:3>.withTag({tier: 3}), <mekanism:basicblock2:3>.withTag({tier: 3}), <environmentaltech:solar_cont_6>, <mekanism:basicblock2:3>.withTag({tier: 3}), <mekanism:basicblock2:3>.withTag({tier: 3}), <mekanism:basicblock2:3>.withTag({tier: 3}), <mekanism:energycube>.withTag({tier: 3, mekData: {energyStored: 1.28E8}})]
]);

/* Creative Flux Capacitor */
mods.extendedcrafting.TableCrafting.addShaped(0, <draconicevolution:draconium_capacitor:2>, [
	[<fluxnetworks:gargantuanfluxstorage>, <randomthings:spectrecharger:2>, <randomthings:spectrecharger:2>, <randomthings:spectrecharger:2>, <draconicevolution:chaotic_core>, <randomthings:spectrecharger:2>, <randomthings:spectrecharger:2>, <randomthings:spectrecharger:2>, <fluxnetworks:gargantuanfluxstorage>], 
	[<randomthings:spectrecharger:2>, <redstonearsenal:storage>, <redstonearsenal:storage>, <draconicevolution:flow_gate>, <draconicevolution:flow_gate>, <draconicevolution:flow_gate>, <redstonearsenal:storage>, <redstonearsenal:storage>, <randomthings:spectrecharger:2>], 
	[<randomthings:spectrecharger:2>, <redstonearsenal:storage>, <projectex:power_flower:15>, <enderio:block_transceiver>, <opencomputers:powerdistributor>, <enderio:block_transceiver>, <opencomputers:powerdistributor>, <redstonearsenal:storage>, <randomthings:spectrecharger:2>], 
	[<randomthings:spectrecharger:2>, <draconicevolution:flow_gate>, <enderio:block_transceiver>, <nuclearcraft:depleted_fuel_curium:5>, <fluxnetworks:fluxplug>, <nuclearcraft:depleted_fuel_curium:5>, <enderio:block_transceiver>, <draconicevolution:flow_gate>, <randomthings:spectrecharger:2>], 
	[<draconicevolution:chaotic_core>, <draconicevolution:flow_gate>, <opencomputers:powerdistributor>, <fluxnetworks:fluxplug>, <extendedcrafting:singularity_ultimate>, <fluxnetworks:fluxplug>, <opencomputers:powerdistributor>, <draconicevolution:flow_gate>, <draconicevolution:chaotic_core>], 
	[<randomthings:spectrecharger:2>, <draconicevolution:flow_gate>, <enderio:block_transceiver>, <nuclearcraft:depleted_fuel_curium:5>, <fluxnetworks:fluxplug>, <nuclearcraft:depleted_fuel_curium:5>, <enderio:block_transceiver>, <draconicevolution:flow_gate>, <randomthings:spectrecharger:2>], 
	[<randomthings:spectrecharger:2>, <redstonearsenal:storage>, <opencomputers:powerdistributor>, <enderio:block_transceiver>, <opencomputers:powerdistributor>, <enderio:block_transceiver>, <projectex:power_flower:15>, <redstonearsenal:storage>, <randomthings:spectrecharger:2>], 
	[<randomthings:spectrecharger:2>, <redstonearsenal:storage>, <redstonearsenal:storage>, <draconicevolution:flow_gate>, <draconicevolution:flow_gate>, <draconicevolution:flow_gate>, <redstonearsenal:storage>, <redstonearsenal:storage>, <randomthings:spectrecharger:2>], 
	[<fluxnetworks:gargantuanfluxstorage>, <randomthings:spectrecharger:2>, <randomthings:spectrecharger:2>, <randomthings:spectrecharger:2>, <draconicevolution:chaotic_core>, <randomthings:spectrecharger:2>, <randomthings:spectrecharger:2>, <randomthings:spectrecharger:2>, <fluxnetworks:gargantuanfluxstorage>]
]);

/* Creative Fluid Tank */
mods.extendedcrafting.TableCrafting.addShaped(0, <mekanism:machineblock2:11>.withTag({tier: 4}), [
	[<mekanism:machineblock2:11>.withTag({tier: 3, mekData: {fluidTank: {FluidName: "swamp_water", Amount: 112000}}}), <enderstorage:ender_storage:1>, <enderstorage:ender_storage:1>, <enderstorage:ender_storage:1>, <bloodmagic:blood_tank:15>, <enderstorage:ender_storage:1>, <enderstorage:ender_storage:1>, <enderstorage:ender_storage:1>, <mekanism:machineblock2:11>.withTag({tier: 3, mekData: {fluidTank: {FluidName: "lava", Amount: 112000}}})], 
	[<extracells:certustank>, <extracells:storage.fluid:6>, <draconicevolution:flow_gate:8>, <draconicevolution:flow_gate:8>, <enderutilities:enderbucket>, <draconicevolution:flow_gate:8>, <draconicevolution:flow_gate:8>, <extracells:storage.fluid:6>, <extracells:certustank>], 
	[<extracells:certustank>, <projecte:item.pe_evertide_amulet>, <mekanism:basicblock:9>, <mekanism:basicblock:9>, <mekanism:basicblock:9>, <mekanism:basicblock:9>, <mekanism:basicblock:9>, <projecte:item.pe_evertide_amulet>, <extracells:certustank>], 
	[<extracells:certustank>, <projecte:item.pe_volcanite_amulet>, <mekanism:basicblock:9>, <industrialforegoing:black_hole_tank>, <industrialforegoing:black_hole_tank>, <industrialforegoing:black_hole_tank>, <mekanism:basicblock:9>, <projecte:item.pe_volcanite_amulet>, <extracells:certustank>], 
	[<extracells:certustank>, <thebetweenlands:bl_bucket:1>, <mekanism:basicblock:9>, <industrialforegoing:black_hole_tank>, <extendedcrafting:singularity_ultimate>, <industrialforegoing:black_hole_tank>, <mekanism:basicblock:9>, <botania:openbucket>, <extracells:certustank>], 
	[<extracells:certustank>, <projecte:item.pe_volcanite_amulet>, <mekanism:basicblock:9>, <industrialforegoing:black_hole_tank>, <industrialforegoing:black_hole_tank>, <industrialforegoing:black_hole_tank>, <mekanism:basicblock:9>, <projecte:item.pe_volcanite_amulet>, <extracells:certustank>], 
	[<extracells:certustank>, <projecte:item.pe_evertide_amulet>, <mekanism:basicblock:9>, <mekanism:basicblock:9>, <mekanism:basicblock:9>, <mekanism:basicblock:9>, <mekanism:basicblock:9>, <projecte:item.pe_evertide_amulet>, <extracells:certustank>], 
	[<extracells:certustank>, <extracells:storage.fluid:6>, <draconicevolution:flow_gate:8>, <draconicevolution:flow_gate:8>, <randomthings:reinforcedenderbucket>, <draconicevolution:flow_gate:8>, <draconicevolution:flow_gate:8>, <extracells:storage.fluid:6>, <extracells:certustank>], 
	[<mekanism:machineblock2:11>.withTag({tier: 3, mekData: {fluidTank: {FluidName: "redstone", Amount: 112000}}}), <enderstorage:ender_storage:1>, <enderstorage:ender_storage:1>, <enderstorage:ender_storage:1>, <bloodmagic:blood_tank:15>, <enderstorage:ender_storage:1>, <enderstorage:ender_storage:1>, <enderstorage:ender_storage:1>, <mekanism:machineblock2:11>.withTag({tier: 3, mekData: {fluidTank: {FluidName: "lapis", Amount: 112000}}})]
]);

/* Creative Gas Tank */
mods.extendedcrafting.TableCrafting.addShaped(0, <mekanism:gastank>.withTag({tier: 4}), [
	[<extracells:storage.gas:6>, <mekanismgenerators:generator:3>, <mekanism:transmitter:2>.withTag({tier: 3}), <mekanism:transmitter:2>.withTag({tier: 3}), <extracells:storage.gas:6>, <mekanism:transmitter:2>.withTag({tier: 3}), <mekanism:transmitter:2>.withTag({tier: 3}), <mekanism:machineblock2:4>, <extracells:storage.gas:6>], 
	[<mekanismgenerators:generator:3>, <mekanism:gastank>.withTag({tier: 3, mekData: {stored: {amount: 512000, gasName: "hydrogen"}}}), <mekanism:transmitter:2>.withTag({tier: 3}), <mekanism:transmitter:2>.withTag({tier: 3}), <mekanism:gastank>.withTag({tier: 3, mekData: {stored: {amount: 512000, gasName: "oxygen"}}}), <mekanism:transmitter:2>.withTag({tier: 3}), <mekanism:transmitter:2>.withTag({tier: 3}), <mekanism:gastank>.withTag({tier: 3, mekData: {stored: {amount: 512000, gasName: "chlorine"}}}), <mekanism:machineblock2:4>], 
	[<mekanism:transmitter:2>.withTag({tier: 3}), <mekanism:transmitter:2>.withTag({tier: 3}), <mekanism:machineblock2:10>, <mekanism:gasupgrade>, <nuclearcraft:electrolyzer>, <mekanism:gasupgrade>, <mekanism:machineblock2:10>, <mekanism:transmitter:2>.withTag({tier: 3}), <mekanism:transmitter:2>.withTag({tier: 3})], 
	[<mekanism:transmitter:2>.withTag({tier: 3}), <mekanism:transmitter:2>.withTag({tier: 3}), <mekanism:gasupgrade>, <nuclearcraft:nitrogen_collector_dense>, <mekanism:controlcircuit:3>, <nuclearcraft:nitrogen_collector_dense>, <mekanism:gasupgrade>, <mekanism:transmitter:2>.withTag({tier: 3}), <mekanism:transmitter:2>.withTag({tier: 3})], 
	[<extracells:storage.gas:6>, <mekanism:gastank>.withTag({tier: 3, mekData: {stored: {amount: 512000, gasName: "sulfurtrioxide"}}}), <nuclearcraft:electrolyzer>, <mekanism:controlcircuit:3>, <extendedcrafting:singularity_ultimate>, <mekanism:controlcircuit:3>, <nuclearcraft:electrolyzer>, <mekanism:gastank>.withTag({tier: 3, mekData: {stored: {amount: 512000, gasName: "sulfuricacid"}}}), <extracells:storage.gas:6>], 
	[<mekanism:transmitter:2>.withTag({tier: 3}), <mekanism:transmitter:2>.withTag({tier: 3}), <mekanism:gasupgrade>, <nuclearcraft:nitrogen_collector_dense>, <mekanism:controlcircuit:3>, <nuclearcraft:nitrogen_collector_dense>, <mekanism:gasupgrade>, <mekanism:transmitter:2>.withTag({tier: 3}), <mekanism:transmitter:2>.withTag({tier: 3})], 
	[<mekanism:transmitter:2>.withTag({tier: 3}), <mekanism:transmitter:2>.withTag({tier: 3}), <mekanism:machineblock2:10>, <mekanism:gasupgrade>, <nuclearcraft:electrolyzer>, <mekanism:gasupgrade>, <mekanism:machineblock2:10>, <mekanism:transmitter:2>.withTag({tier: 3}), <mekanism:transmitter:2>.withTag({tier: 3})], 
	[<mekanism:machineblock2:4>, <mekanism:gastank>.withTag({tier: 3, mekData: {stored: {amount: 512000, gasName: "ethene"}}}), <mekanism:transmitter:2>.withTag({tier: 3}), <mekanism:transmitter:2>.withTag({tier: 3}), <mekanism:gastank>.withTag({tier: 3, mekData: {stored: {amount: 512000, gasName: "brine"}}}), <mekanism:transmitter:2>.withTag({tier: 3}), <mekanism:transmitter:2>.withTag({tier: 3}), <mekanism:gastank>.withTag({tier: 3, mekData: {stored: {amount: 512000, gasName: "fusionfuel"}}}), <mekanismgenerators:generator:3>], 
	[<extracells:storage.gas:6>, <mekanism:machineblock2:4>, <mekanism:transmitter:2>.withTag({tier: 3}), <mekanism:transmitter:2>.withTag({tier: 3}), <extracells:storage.gas:6>, <mekanism:transmitter:2>.withTag({tier: 3}), <mekanism:transmitter:2>.withTag({tier: 3}), <mekanismgenerators:generator:3>, <extracells:storage.gas:6>]
]);

/* Creative Vending Upgrade */
mods.extendedcrafting.TableCrafting.addShaped(0, <storagedrawers:upgrade_creative:1> * 2, [
	[<extrautils2:passivegenerator:6>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_storage:4>, <wct:wct_creative>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_storage:4>, <bloodmagic:sacrificial_dagger:1>], 
	[<storagedrawers:upgrade_storage:4>, <storagedrawers:controller>, <mekanism:basicblock:6>.withTag({tier: 3}), <enderio:block_inventory_chest_warehouse13>, <abyssalcraft:transmutationgem>, <enderio:block_inventory_chest_warehouse13>, <mekanism:basicblock:6>.withTag({tier: 3}), <storagedrawers:controller>, <storagedrawers:upgrade_storage:4>], 
	[<storagedrawers:upgrade_storage:4>, <enderutilities:barrel>, <storagenetwork:master>, <actuallyadditions:block_giant_chest_large>, <industrialforegoing:black_hole_unit>, <actuallyadditions:block_giant_chest_large>, <storagenetwork:master>, <enderutilities:barrel>, <storagedrawers:upgrade_storage:4>], 
	[<storagedrawers:upgrade_storage:4>, <rftools:modular_storage>, <extendedcrafting:table_ultimate>, <extendedcrafting:singularity_ultimate>, <extracells:storage.physical:3>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:table_ultimate>, <rftools:modular_storage>, <storagedrawers:upgrade_storage:4>], 
	[<mekanism:machineblock2:11>.withTag({tier: 4}), <projectex:power_flower:15>, <industrialforegoing:black_hole_unit>, <extracells:storage.physical:3>, <mekanism:energycube>.withTag({tier: 4}), <extracells:storage.physical:3>, <industrialforegoing:black_hole_unit>, <projectex:power_flower:15>, <mekanism:gastank>.withTag({tier: 4})], 
	[<storagedrawers:upgrade_storage:4>, <rftools:modular_storage>, <extendedcrafting:table_ultimate>, <extendedcrafting:singularity_ultimate>, <extracells:storage.physical:3>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:table_ultimate>, <rftools:modular_storage>, <storagedrawers:upgrade_storage:4>], 
	[<storagedrawers:upgrade_storage:4>, <enderutilities:barrel>, <storagenetwork:master>, <actuallyadditions:block_giant_chest_large>, <industrialforegoing:black_hole_unit>, <actuallyadditions:block_giant_chest_large>, <storagenetwork:master>, <enderutilities:barrel>, <storagedrawers:upgrade_storage:4>], 
	[<storagedrawers:upgrade_storage:4>, <storagedrawers:controller>, <mekanism:basicblock:6>.withTag({tier: 3}), <enderio:block_inventory_chest_warehouse13>, <abyssalcraft:transmutationgem>, <enderio:block_inventory_chest_warehouse13>, <mekanism:basicblock:6>.withTag({tier: 3}), <storagedrawers:controller>, <storagedrawers:upgrade_storage:4>], 
	[<tconstruct:materials:50>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_storage:4>, <draconicevolution:draconium_capacitor:2>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_storage:4>, <deepmoblearning:creative_model_learner>]
]);

/* Creative Fluxbore */
mods.extendedcrafting.TableCrafting.addShaped(0, <thermalinnovation:drill:32000>.withTag({Energy: 600000, Mode: 4}), [
	[<tconstruct:hammer_head>.withTag({Material: "dreadium"}), <projecte:item.pe_dm_hammer>, <actuallyadditions:wooden_paxel>, <actuallyadditions:stone_paxel>, <tconstruct:hammer_head>.withTag({Material: "manyullyn"}), <actuallyadditions:iron_paxel>, <actuallyadditions:gold_paxel>, <projecte:item.pe_dm_hammer>, <tconstruct:hammer_head>.withTag({Material: "knightslime"})], 
	[<projecte:item.pe_rm_hammer>, <extrautils2:compressedcobblestone:1>, <extrautils2:compressedcobblestone:1>, <extrautils2:compressedcobblestone:1>, <extrautils2:compressedcobblestone:1>, <extrautils2:compressedcobblestone:1>, <extrautils2:compressedcobblestone:1>, <extrautils2:compressedcobblestone:1>, <projecte:item.pe_rm_hammer>], 
	[<actuallyadditions:diamond_paxel>, <extrautils2:compressedcobblestone:1>, <minecraft:emerald_ore>, <minecraft:lapis_ore>, <minecraft:diamond_ore>, <minecraft:lapis_ore>, <minecraft:emerald_ore>, <extrautils2:compressedcobblestone:1>, <actuallyadditions:emerald_paxel>], 
	[<actuallyadditions:obsidian_paxel>, <extrautils2:compressedcobblestone:1>, <minecraft:redstone_ore>, <redstonearsenal:tool.hammer_flux>, <thermalinnovation:drill:4>, <redstonearsenal:tool.hammer_flux>, <minecraft:redstone_ore>, <extrautils2:compressedcobblestone:1>, <actuallyadditions:quartz_paxel>], 
	[<tconstruct:hammer_head>.withTag({Material: "hard_carbon"}), <extrautils2:compressedcobblestone:1>, <minecraft:diamond_ore>, <thermalinnovation:drill:4>, <extendedcrafting:singularity_ultimate>, <thermalinnovation:drill:4>, <minecraft:diamond_ore>, <extrautils2:compressedcobblestone:1>, <tconstruct:hammer_head>.withTag({Material: "pigiron"})], 
	[<actuallyadditions:item_paxel_crystal_red>, <extrautils2:compressedcobblestone:1>, <minecraft:redstone_ore>, <redstonearsenal:tool.hammer_flux>, <thermalinnovation:drill:4>, <redstonearsenal:tool.hammer_flux>, <minecraft:redstone_ore>, <extrautils2:compressedcobblestone:1>, <actuallyadditions:item_paxel_crystal_blue>], 
	[<actuallyadditions:item_paxel_crystal_light_blue>, <extrautils2:compressedcobblestone:1>, <minecraft:emerald_ore>, <minecraft:lapis_ore>, <minecraft:diamond_ore>, <minecraft:lapis_ore>, <minecraft:emerald_ore>, <extrautils2:compressedcobblestone:1>, <actuallyadditions:item_paxel_crystal_black>], 
	[<projecte:item.pe_rm_hammer>, <extrautils2:compressedcobblestone:1>, <extrautils2:compressedcobblestone:1>, <extrautils2:compressedcobblestone:1>, <extrautils2:compressedcobblestone:1>, <extrautils2:compressedcobblestone:1>, <extrautils2:compressedcobblestone:1>, <extrautils2:compressedcobblestone:1>, <projecte:item.pe_rm_hammer>], 
	[<tconstruct:hammer_head>.withTag({Material: "xu_evil_metal"}), <projecte:item.pe_dm_hammer>, <actuallyadditions:item_paxel_crystal_green>, <botania:manasteelpick>, <tconstruct:hammer_head>.withTag({Material: "end_steel"}), <botania:elementiumpick>, <actuallyadditions:item_paxel_crystal_white>, <projecte:item.pe_dm_hammer>, <tconstruct:hammer_head>.withTag({Material: "integrationforegoing.reinforced_pink_slime"})]
]);

/* Creative Fluxsaw */
mods.extendedcrafting.TableCrafting.addShaped(0, <thermalinnovation:saw:32000>.withTag({Energy: 600000, Mode: 4}), [
	[<tconstruct:broad_axe_head>.withTag({Material: "dreadium"}), <thebetweenlands:log_weedwood>, <actuallyadditions:wooden_paxel>, <actuallyadditions:stone_paxel>, <tconstruct:broad_axe_head>.withTag({Material: "manyullyn"}), <actuallyadditions:iron_paxel>, <actuallyadditions:gold_paxel>, <thebetweenlands:log_weedwood>, <tconstruct:broad_axe_head>.withTag({Material: "knightslime"})], 
	[<thebetweenlands:log_hearthgrove:1>, <tconstruct:firewood:1>, <tconstruct:firewood:1>, <tconstruct:firewood:1>, <tconstruct:firewood:1>, <tconstruct:firewood:1>, <tconstruct:firewood:1>, <tconstruct:firewood:1>, <thebetweenlands:log_hearthgrove:1>], 
	[<actuallyadditions:diamond_paxel>, <tconstruct:firewood:1>, <thebetweenlands:log_nibbletwig>, <astralsorcery:blockinfusedwood>, <thebetweenlands:log_sap>, <astralsorcery:blockinfusedwood>, <thebetweenlands:log_nibbletwig>, <tconstruct:firewood:1>, <actuallyadditions:emerald_paxel>], 
	[<actuallyadditions:obsidian_paxel>, <tconstruct:firewood:1>, <botania:dreamwood>, <thermalinnovation:saw:4>, <mekanism:machineblock2:5>, <thermalinnovation:saw:4>, <botania:dreamwood>, <tconstruct:firewood:1>, <actuallyadditions:quartz_paxel>], 
	[<tconstruct:broad_axe_head>.withTag({Material: "hard_carbon"}), <tconstruct:firewood:1>, <thebetweenlands:log_sap>, <mekanism:machineblock2:5>, <extendedcrafting:singularity_ultimate>, <mekanism:machineblock2:5>, <thebetweenlands:log_sap>, <tconstruct:firewood:1>, <tconstruct:broad_axe_head>.withTag({Material: "pigiron"})], 
	[<actuallyadditions:item_paxel_crystal_red>, <tconstruct:firewood:1>, <botania:dreamwood>, <thermalinnovation:saw:4>, <mekanism:machineblock2:5>, <thermalinnovation:saw:4>, <botania:dreamwood>, <tconstruct:firewood:1>, <actuallyadditions:item_paxel_crystal_blue>], 
	[<actuallyadditions:item_paxel_crystal_light_blue>, <tconstruct:firewood:1>, <thebetweenlands:log_nibbletwig>, <astralsorcery:blockinfusedwood>, <thebetweenlands:log_sap>, <astralsorcery:blockinfusedwood>, <thebetweenlands:log_nibbletwig>, <tconstruct:firewood:1>, <actuallyadditions:item_paxel_crystal_black>], 
	[<thebetweenlands:log_hearthgrove:1>, <tconstruct:firewood:1>, <tconstruct:firewood:1>, <tconstruct:firewood:1>, <tconstruct:firewood:1>, <tconstruct:firewood:1>, <tconstruct:firewood:1>, <tconstruct:firewood:1>, <thebetweenlands:log_hearthgrove:1>], 
	[<tconstruct:broad_axe_head>.withTag({Material: "xu_evil_metal"}), <thebetweenlands:log_weedwood>, <actuallyadditions:item_paxel_crystal_green>, <botania:manasteelaxe>, <tconstruct:broad_axe_head>.withTag({Material: "end_steel"}), <botania:elementiumaxe>, <actuallyadditions:item_paxel_crystal_white>, <thebetweenlands:log_weedwood>, <tconstruct:broad_axe_head>.withTag({Material: "integrationforegoing.reinforced_pink_slime"})]
]);

/* Creative Magnet */
mods.extendedcrafting.TableCrafting.addShaped(0, <thermalinnovation:magnet:32000>.withTag({Energy: 600000}), [
	[<minecraft:potion>.withTag({Potion: "cyclicmagic:magnet"}), <bloodmagic:sigil_magnetism>, <bloodmagic:sigil_magnetism>, <bloodmagic:sigil_magnetism>, <minecraft:potion>.withTag({Potion: "cyclicmagic:magnet"}), <bloodmagic:sigil_magnetism>, <bloodmagic:sigil_magnetism>, <bloodmagic:sigil_magnetism>, <minecraft:potion>.withTag({Potion: "cyclicmagic:magnet"})], 
	[<bloodmagic:sigil_magnetism>, <enderio:item_magnet>, <actuallyadditions:item_suction_ring>, <actuallyadditions:item_suction_ring>, <actuallyadditions:item_suction_ring>, <actuallyadditions:item_suction_ring>, <actuallyadditions:item_suction_ring>, <enderio:item_magnet>, <bloodmagic:sigil_magnetism>], 
	[<bloodmagic:sigil_magnetism>, <mekanismgenerators:generator:9>, <mekanismgenerators:generator:9>, <mekanismgenerators:generator:9>, <mekanismgenerators:generator:9>, <mekanismgenerators:generator:9>, <mekanismgenerators:generator:9>, <mekanismgenerators:generator:9>, <bloodmagic:sigil_magnetism>], 
	[<bloodmagic:sigil_magnetism>, <mekanismgenerators:generator:9>, <mekanismgenerators:generator:9>, <minecraft:potion>.withTag({Potion: "cyclicmagic:magnet"}), <thermalinnovation:magnet:4>, <minecraft:potion>.withTag({Potion: "cyclicmagic:magnet"}), <mekanismgenerators:generator:9>, <mekanismgenerators:generator:9>, <bloodmagic:sigil_magnetism>], 
	[<minecraft:potion>.withTag({Potion: "cyclicmagic:magnet"}), <mekanismgenerators:generator:9>, <mekanismgenerators:generator:9>, <thermalinnovation:magnet:4>, <extendedcrafting:singularity_ultimate>, <thermalinnovation:magnet:4>, <mekanismgenerators:generator:9>, <mekanismgenerators:generator:9>, <minecraft:potion>.withTag({Potion: "cyclicmagic:magnet"})], 
	[<bloodmagic:sigil_magnetism>, <mekanismgenerators:generator:9>, <mekanismgenerators:generator:9>, <minecraft:potion>.withTag({Potion: "cyclicmagic:magnet"}), <thermalinnovation:magnet:4>, <minecraft:potion>.withTag({Potion: "cyclicmagic:magnet"}), <mekanismgenerators:generator:9>, <mekanismgenerators:generator:9>, <bloodmagic:sigil_magnetism>], 
	[<bloodmagic:sigil_magnetism>, <mekanismgenerators:generator:9>, <mekanismgenerators:generator:9>, <mekanismgenerators:generator:9>, <mekanismgenerators:generator:9>, <mekanismgenerators:generator:9>, <mekanismgenerators:generator:9>, <mekanismgenerators:generator:9>, <bloodmagic:sigil_magnetism>], 
	[<bloodmagic:sigil_magnetism>, <enderio:item_magnet>, <actuallyadditions:item_suction_ring>, <actuallyadditions:item_suction_ring>, <actuallyadditions:item_suction_ring>, <actuallyadditions:item_suction_ring>, <actuallyadditions:item_suction_ring>, <enderio:item_magnet>, <bloodmagic:sigil_magnetism>], 
	[<minecraft:potion>.withTag({Potion: "cyclicmagic:magnet"}), <bloodmagic:sigil_magnetism>, <bloodmagic:sigil_magnetism>, <bloodmagic:sigil_magnetism>, <minecraft:potion>.withTag({Potion: "cyclicmagic:magnet"}), <bloodmagic:sigil_magnetism>, <bloodmagic:sigil_magnetism>, <bloodmagic:sigil_magnetism>, <minecraft:potion>.withTag({Potion: "cyclicmagic:magnet"})]
]);

/* Creative Hypoinfuser */
mods.extendedcrafting.TableCrafting.addShaped(0, <thermalinnovation:injector:32000>.withTag({}), [
	[<minecraft:potion>.withTag({Potion: "minecraft:long_night_vision"}), <minecraft:potion>.withTag({Potion: "minecraft:long_invisibility"}), <minecraft:potion>.withTag({Potion: "minecraft:long_leaping"}), <minecraft:potion>.withTag({Potion: "minecraft:long_fire_resistance"}), <minecraft:potion>.withTag({Potion: "quark:long_haste"}), <minecraft:potion>.withTag({Potion: "minecraft:long_fire_resistance"}), <minecraft:potion>.withTag({Potion: "minecraft:long_leaping"}), <minecraft:potion>.withTag({Potion: "minecraft:long_invisibility"}), <minecraft:potion>.withTag({Potion: "minecraft:long_night_vision"})], 
	[<minecraft:potion>.withTag({Potion: "minecraft:long_swiftness"}), <minecraft:potion>.withTag({Potion: "minecraft:long_water_breathing"}), <minecraft:potion>.withTag({Potion: "minecraft:strong_healing"}), <minecraft:potion>.withTag({Potion: "minecraft:long_regeneration"}), <minecraft:potion>.withTag({Potion: "quark:long_resistance"}), <minecraft:potion>.withTag({Potion: "minecraft:long_regeneration"}), <minecraft:potion>.withTag({Potion: "minecraft:strong_healing"}), <minecraft:potion>.withTag({Potion: "minecraft:long_water_breathing"}), <minecraft:potion>.withTag({Potion: "minecraft:long_swiftness"})], 
	[<minecraft:potion>.withTag({Potion: "minecraft:long_strength"}), <minecraft:potion>.withTag({Potion: "cofhcore:luck+"}), <minecraft:potion>.withTag({Potion: "apotheosis:long_absorption"}), <minecraft:potion>.withTag({Potion: "cyclicmagic:slowfall"}), <minecraft:potion>.withTag({Potion: "quark:long_resilience"}), <minecraft:potion>.withTag({Potion: "cyclicmagic:slowfall"}), <minecraft:potion>.withTag({Potion: "apotheosis:long_absorption"}), <minecraft:potion>.withTag({Potion: "cofhcore:luck+"}), <minecraft:potion>.withTag({Potion: "minecraft:long_strength"})], 
	[<minecraft:potion>.withTag({Potion: "cyclicmagic:waterwalk"}), <minecraft:potion>.withTag({Potion: "cyclicmagic:swim"}), <minecraft:potion>.withTag({Potion: "cyclicmagic:saturation"}), <industrialforegoing:potion_enervator>, <thermalinnovation:injector:4>.withTag({}), <industrialforegoing:potion_enervator>, <minecraft:potion>.withTag({Potion: "cyclicmagic:saturation"}), <minecraft:potion>.withTag({Potion: "cyclicmagic:swim"}), <minecraft:potion>.withTag({Potion: "cyclicmagic:waterwalk"})], 
	[<minecraft:potion>.withTag({Potion: "quark:long_haste"}), <minecraft:potion>.withTag({Potion: "quark:long_resistance"}), <minecraft:potion>.withTag({Potion: "quark:long_resilience"}), <thermalinnovation:injector:4>.withTag({}), <extendedcrafting:singularity_ultimate>, <thermalinnovation:injector:4>.withTag({}), <minecraft:potion>.withTag({Potion: "quark:long_resilience"}), <minecraft:potion>.withTag({Potion: "quark:long_resistance"}), <minecraft:potion>.withTag({Potion: "quark:long_haste"})], 
	[<minecraft:potion>.withTag({Potion: "cyclicmagic:waterwalk"}), <minecraft:potion>.withTag({Potion: "cyclicmagic:swim"}), <minecraft:potion>.withTag({Potion: "cyclicmagic:saturation"}), <industrialforegoing:potion_enervator>, <thermalinnovation:injector:4>.withTag({}), <industrialforegoing:potion_enervator>, <minecraft:potion>.withTag({Potion: "cyclicmagic:saturation"}), <minecraft:potion>.withTag({Potion: "cyclicmagic:swim"}), <minecraft:potion>.withTag({Potion: "cyclicmagic:waterwalk"})], 
	[<minecraft:potion>.withTag({Potion: "minecraft:long_strength"}), <minecraft:potion>.withTag({Potion: "cofhcore:luck+"}), <minecraft:potion>.withTag({Potion: "apotheosis:long_absorption"}), <minecraft:potion>.withTag({Potion: "cyclicmagic:slowfall"}), <minecraft:potion>.withTag({Potion: "quark:long_resilience"}), <minecraft:potion>.withTag({Potion: "cyclicmagic:slowfall"}), <minecraft:potion>.withTag({Potion: "apotheosis:long_absorption"}), <minecraft:potion>.withTag({Potion: "cofhcore:luck+"}), <minecraft:potion>.withTag({Potion: "minecraft:long_strength"})], 
	[<minecraft:potion>.withTag({Potion: "minecraft:long_swiftness"}), <minecraft:potion>.withTag({Potion: "minecraft:long_water_breathing"}), <minecraft:potion>.withTag({Potion: "minecraft:strong_healing"}), <minecraft:potion>.withTag({Potion: "minecraft:long_regeneration"}), <minecraft:potion>.withTag({Potion: "quark:long_resistance"}), <minecraft:potion>.withTag({Potion: "minecraft:long_regeneration"}), <minecraft:potion>.withTag({Potion: "minecraft:strong_healing"}), <minecraft:potion>.withTag({Potion: "minecraft:long_water_breathing"}), <minecraft:potion>.withTag({Potion: "minecraft:long_swiftness"})], 
	[<minecraft:potion>.withTag({Potion: "minecraft:long_night_vision"}), <minecraft:potion>.withTag({Potion: "minecraft:long_invisibility"}), <minecraft:potion>.withTag({Potion: "minecraft:long_leaping"}), <minecraft:potion>.withTag({Potion: "minecraft:long_fire_resistance"}), <minecraft:potion>.withTag({Potion: "quark:long_haste"}), <minecraft:potion>.withTag({Potion: "minecraft:long_fire_resistance"}), <minecraft:potion>.withTag({Potion: "minecraft:long_leaping"}), <minecraft:potion>.withTag({Potion: "minecraft:long_invisibility"}), <minecraft:potion>.withTag({Potion: "minecraft:long_night_vision"})]
]);

/* Creative Alchemical Quiver */
mods.extendedcrafting.TableCrafting.addShaped(0, <thermalinnovation:quiver:32000>.withTag({}), [
	[<minecraft:potion>.withTag({Potion: "minecraft:long_slowness"}), <minecraft:potion>.withTag({Potion: "minecraft:strong_harming"}), <minecraft:potion>.withTag({Potion: "minecraft:long_poison"}), <minecraft:potion>.withTag({Potion: "minecraft:long_weakness"}), <quark:arrow_explosive>, <minecraft:potion>.withTag({Potion: "minecraft:long_weakness"}), <minecraft:potion>.withTag({Potion: "minecraft:long_poison"}), <minecraft:potion>.withTag({Potion: "minecraft:strong_harming"}), <minecraft:potion>.withTag({Potion: "minecraft:long_slowness"})], 
	[<minecraft:potion>.withTag({Potion: "apotheosis:long_fatigue"}), <minecraft:potion>.withTag({Potion: "apotheosis:long_wither"}), <minecraft:potion>.withTag({Potion: "cofhcore:levitation+"}), <minecraft:potion>.withTag({Potion: "cofhcore:unluck+"}), <quark:arrow_explosive>, <minecraft:potion>.withTag({Potion: "cofhcore:unluck+"}), <minecraft:potion>.withTag({Potion: "cofhcore:levitation+"}), <minecraft:potion>.withTag({Potion: "apotheosis:long_wither"}), <minecraft:potion>.withTag({Potion: "apotheosis:long_fatigue"})], 
	[<minecraft:potion>.withTag({Potion: "cyclicmagic:butter2"}), <minecraft:potion>.withTag({Potion: "cyclicmagic:blindness"}), <minecraft:potion>.withTag({Potion: "cyclicmagic:hunger"}), <minecraft:potion>.withTag({Potion: "randomthings:long_collapse"}), <quark:arrow_explosive>, <minecraft:potion>.withTag({Potion: "randomthings:long_collapse"}), <minecraft:potion>.withTag({Potion: "cyclicmagic:hunger"}), <minecraft:potion>.withTag({Potion: "cyclicmagic:blindness"}), <minecraft:potion>.withTag({Potion: "cyclicmagic:butter2"})], 
	[<minecraft:potion>.withTag({Potion: "enderio:long_confusion"}), <minecraft:potion>.withTag({Potion: "extrautils2:xu2.doom"}), <minecraft:potion>.withTag({Potion: "extrautils2:xu2.gravity.long"}), <botania:alchemycatalyst>, <thermalinnovation:quiver:4>.withTag({}), <botania:alchemycatalyst>, <minecraft:potion>.withTag({Potion: "extrautils2:xu2.gravity.long"}), <minecraft:potion>.withTag({Potion: "extrautils2:xu2.doom"}), <minecraft:potion>.withTag({Potion: "enderio:long_confusion"})], 
	[<quark:arrow_explosive>, <quark:arrow_explosive>, <quark:arrow_explosive>, <thermalinnovation:quiver:4>.withTag({}), <extendedcrafting:singularity_ultimate>, <thermalinnovation:quiver:4>.withTag({}), <quark:arrow_explosive>, <quark:arrow_explosive>, <quark:arrow_explosive>], 
	[<minecraft:potion>.withTag({Potion: "enderio:long_confusion"}), <minecraft:potion>.withTag({Potion: "extrautils2:xu2.doom"}), <minecraft:potion>.withTag({Potion: "extrautils2:xu2.gravity.long"}), <botania:alchemycatalyst>, <thermalinnovation:quiver:4>.withTag({}), <botania:alchemycatalyst>, <minecraft:potion>.withTag({Potion: "extrautils2:xu2.gravity.long"}), <minecraft:potion>.withTag({Potion: "extrautils2:xu2.doom"}), <minecraft:potion>.withTag({Potion: "enderio:long_confusion"})], 
	[<minecraft:potion>.withTag({Potion: "cyclicmagic:butter2"}), <minecraft:potion>.withTag({Potion: "cyclicmagic:blindness"}), <minecraft:potion>.withTag({Potion: "cyclicmagic:hunger"}), <minecraft:potion>.withTag({Potion: "randomthings:long_collapse"}), <quark:arrow_explosive>, <minecraft:potion>.withTag({Potion: "randomthings:long_collapse"}), <minecraft:potion>.withTag({Potion: "cyclicmagic:hunger"}), <minecraft:potion>.withTag({Potion: "cyclicmagic:blindness"}), <minecraft:potion>.withTag({Potion: "cyclicmagic:butter2"})], 
	[<minecraft:potion>.withTag({Potion: "apotheosis:long_fatigue"}), <minecraft:potion>.withTag({Potion: "apotheosis:long_wither"}), <minecraft:potion>.withTag({Potion: "cofhcore:levitation+"}), <minecraft:potion>.withTag({Potion: "cofhcore:unluck+"}), <quark:arrow_explosive>, <minecraft:potion>.withTag({Potion: "cofhcore:unluck+"}), <minecraft:potion>.withTag({Potion: "cofhcore:levitation+"}), <minecraft:potion>.withTag({Potion: "apotheosis:long_wither"}), <minecraft:potion>.withTag({Potion: "apotheosis:long_fatigue"})], 
	[<minecraft:potion>.withTag({Potion: "minecraft:long_slowness"}), <minecraft:potion>.withTag({Potion: "minecraft:strong_harming"}), <minecraft:potion>.withTag({Potion: "minecraft:long_poison"}), <minecraft:potion>.withTag({Potion: "minecraft:long_weakness"}), <quark:arrow_explosive>, <minecraft:potion>.withTag({Potion: "minecraft:long_weakness"}), <minecraft:potion>.withTag({Potion: "minecraft:long_poison"}), <minecraft:potion>.withTag({Potion: "minecraft:strong_harming"}), <minecraft:potion>.withTag({Potion: "minecraft:long_slowness"})]
]);

}
